name: Build Check

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [20.x]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install npm dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run s3-sync-action
        uses: jakejarvis/s3-sync-action@master
        with:
            args: --follow-symlinks --delete
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_S3_BUCKET: ${{ vars.S3_BUCKET }}
            AWS_REGION: "us-east-2"
            SOURCE_DIR: "dist/"
      - name: Run invalidate-cloudfront-action
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: "/*"
          AWS_REGION: "us-east-2"
          DISTRIBUTION: "EG0IMCTJYGOUH"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
